# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_p_pb2 as message__p__pb2


class MessagingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SingleMessage = channel.unary_unary(
                '/Messaging/SingleMessage',
                request_serializer=message__p__pb2.ClientMessage.SerializeToString,
                response_deserializer=message__p__pb2.ServerMessage.FromString,
                )
        self.ServerStream = channel.unary_stream(
                '/Messaging/ServerStream',
                request_serializer=message__p__pb2.ClientMessage.SerializeToString,
                response_deserializer=message__p__pb2.ServerMessage.FromString,
                )
        self.ClientStream = channel.stream_unary(
                '/Messaging/ClientStream',
                request_serializer=message__p__pb2.ClientMessage.SerializeToString,
                response_deserializer=message__p__pb2.ServerMessage.FromString,
                )
        self.TwoWayStream = channel.stream_stream(
                '/Messaging/TwoWayStream',
                request_serializer=message__p__pb2.ClientMessage.SerializeToString,
                response_deserializer=message__p__pb2.ServerMessage.FromString,
                )


class MessagingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SingleMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TwoWayStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SingleMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SingleMessage,
                    request_deserializer=message__p__pb2.ClientMessage.FromString,
                    response_serializer=message__p__pb2.ServerMessage.SerializeToString,
            ),
            'ServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStream,
                    request_deserializer=message__p__pb2.ClientMessage.FromString,
                    response_serializer=message__p__pb2.ServerMessage.SerializeToString,
            ),
            'ClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStream,
                    request_deserializer=message__p__pb2.ClientMessage.FromString,
                    response_serializer=message__p__pb2.ServerMessage.SerializeToString,
            ),
            'TwoWayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TwoWayStream,
                    request_deserializer=message__p__pb2.ClientMessage.FromString,
                    response_serializer=message__p__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Messaging', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Messaging(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SingleMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Messaging/SingleMessage',
            message__p__pb2.ClientMessage.SerializeToString,
            message__p__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Messaging/ServerStream',
            message__p__pb2.ClientMessage.SerializeToString,
            message__p__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Messaging/ClientStream',
            message__p__pb2.ClientMessage.SerializeToString,
            message__p__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TwoWayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Messaging/TwoWayStream',
            message__p__pb2.ClientMessage.SerializeToString,
            message__p__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
